version: '3.8'

services:
  chaisite:
    build:
      context: .
    image: portfolio-img:latest
    container_name: portfolio-cont
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./Portfolio:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro