events {}

http {
    include mime.types;
    default_type application/octet-stream;

    # Redirect HTTP → HTTPS
    server {
        listen 80;
        server_name adityamittal.xyz;
        return 301 https://$host$request_uri;
    }

    # HTTPS server
    server {
        listen 443 ssl;
        server_name adityamittal.xyz;

        ssl_certificate     /etc/letsencrypt/live/adityamittal.xyz/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/adityamittal.xyz/privkey.pem;

        location / {
            proxy_pass http://localhost:30660;   # 🔥 YOUR INGRESS PORT
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}