events {}

http {
    server {
        listen 80;

        root /usr/share/nginx/html;
        index portfolio.html;

        location / {
            try_files $uri $uri/ =404;
        }

        # 🔥 ADD THIS BLOCK (IMPORTANT)
        location ~* \.(css|js|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
            try_files $uri =404;
        }
    }
}