events {}

http {
    server {
        listen 80;

        root /usr/share/nginx/html;
        index portfolio.html;

        location / {
            try_files $uri $uri/ /index.html;
        }
    }
}